### ISSUE TITLE
0.1.0 and HA 2024.8 error (fixed in master)

### ISSUE THREAD

**Issue by mikaelj** [rrooggiieerr/homeassistant-benqprojector#17]
Stack trace:

    2024-09-03 07:58:35.336 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry BenQ w1070/w1250 /dev/ttyUSB0 for benqprojector
    Traceback (most recent call last):
      File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
        result = await component.async_setup_entry(hass, self)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/config/custom_components/benqprojector/__init__.py", line 246, in async_setup_entry
        coordinator = BenQProjectorCoordinator(hass, projector)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/config/custom_components/benqprojector/__init__.py", line 86, in __init__
        model = self.projector.model.upper()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'upper'

I'm guessing https://github.com/rrooggiieerr/homeassistant-benqprojector/commit/4677f6f75e1cbb47a3459307fc3ed57072366e4c fixes it. Mind tagging a release 0.1.1 or something?

Was working before HA upgrade.

**Comment by mikaelj** [comment]
@rrooggiieerr Fixed it, thanks!
